version: '3.8'
services:
  db:
    image: postgres:14
    container_name: apijuros-db
    environment:
      - POSTGRES_DB=ApiJurosDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: